# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 20:54
from __future__ import unicode_literals

import apps.resqpedia_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resqpedia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.LengthGreaterThanTen, apps.resqpedia_app.models.StringAndCertainSymbols])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.LengthGreaterThanTen, apps.resqpedia_app.models.StringAndCertainSymbols])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('comments_for_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to_comment', to='resqpedia_app.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.TextField(default='', validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.StringAndCertainSymbols]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uploaded', to='resqpedia_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_recipe', to='resqpedia_app.User'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.LengthGreaterThanTen, apps.resqpedia_app.models.StringAndCertainSymbols]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.LengthGreaterThanTen, apps.resqpedia_app.models.StringAndCertainSymbols]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.StringAndCertainSymbols]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='number_of_servings',
            field=models.IntegerField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100, validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.StringAndCertainSymbols]),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.OlderThanThirteen]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.EmailRegexMatch, apps.resqpedia_app.models.AlreadyReadyRegistered]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.NameMatchforRegex]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.NameMatchforRegex]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.LengthGreaterThanEight]),
        ),
        migrations.AddField(
            model_name='message',
            name='uploaded_message_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_uploaded', to='resqpedia_app.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_message', to='resqpedia_app.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_uploaded', to='resqpedia_app.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_comments', to='resqpedia_app.User'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='comments_for_recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_with_comments', to='resqpedia_app.Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='messages_for_recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_with_messages', to='resqpedia_app.Message'),
            preserve_default=False,
        ),
    ]
