# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-29 15:15
from __future__ import unicode_literals

import apps.resqpedia_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resqpedia_app', '0002_auto_20190828_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.NoNegatives]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='number_of_servings',
            field=models.IntegerField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.NoNegatives]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.NoNegatives]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[apps.resqpedia_app.models.LengthGreaterThanOne, apps.resqpedia_app.models.LengthGreaterThanEight, apps.resqpedia_app.models.ConfirmPassword]),
        ),
    ]
